### ISSUE TITLE
Make use of Backbone.xmpp and strophe.plugins

### ISSUE THREAD

**Issue by alecghica** [collective/collective.xmpp.core#8]
As @ggozad suggested in #7, we should integrate Backbone.xmpp and strophe.plugins as, I quote: "These are far better than the ones you are using and I will be maintaining them too."

**Comment by jcbrand** [comment]
These are two distinct tasks/issues. 

Backbone.xmpp is for use with PubSub and we don't have any PubSub code at the moment. When the time comes that someone adds PubSub functionality we should definitely look at Backbone.xmpp. But in the current code there is no use-case for it.

https://github.com/ggozad/Backbone.xmpp

Concerning strophe.plugins, we aren't using any plugins or have any need for them in collective.xmpp.core.

We do however use some strophe plugins in collective.xmpp.chat and @ggozad is basically asking us to replace them with plugins he wrote himself. I'm reluctant to do this myself, because even though his plugins are likely better, the chat currently works well and I have very little time or leverage to make changes there. 

I don't have a client who will pay me to replace the strophe plugins and I'd rather spend my free time on other parts.

I would of course be happy if someone else wants to do this, please just do it in a branch then. 
@alecghica You are welcome to create a ticket for this in collective.xmpp.chat if you want to.

Since the strophe plugins are applicable to a different package and we don't have a specific usecase for backbone.xmpp right now, I'm closing this ticket.
